#!/usr/bin/env bash
# a script to configure a new server to install nginx, edit html, redirect a web page

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://github.com/Abd-Elfattah5/simple_shell permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
