#!/usr/bin/env bash
# print for infinit times and print specific message when reciving SIGTERM signal

trap echo "I am invincible!!!" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
