#!/usr/bin/env bash
# solving fizzbuzz as usual

i=1

while [ $i -ne 101 ]
do
	if [ $((i%5)) = 0 ] && [ $((i%3)) = 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i%5)) = 0 ]
	then
		echo "Buzz"
	elif [ $((i%3)) = 0 ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
	((i+=1))
done
