#!/usr/bin/env bash
# printing best school 10 times except 4 and 8

i="0"

while [ $i -ne 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i+=1))
done
