#!/usr/bin/env bash
# printing 20 number with exceptions in 4, 9 and 17

i=1

while [ $i -ne 21 ]
do
	case $i in

		4)
			echo $i
			echo "bad luck from China"
			;;

		9)
			echo $i
			echo "bad luck from Japan"
			;;

		17)
			echo $i
			echo "bad luck from Italy"
			;;

		*)
			echo "$i"
			;;
	esac
	((i+=1))
done
